version: '3.8'

services:
  ecommerce_app:
    image: masteransh/laravel-ecommerce-prateek:3
    container_name: ecommerce_app
    restart: always
    depends_on:
      - proxysql
      - redis
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: proxysql
      DB_PORT: 6033
      DB_DATABASE: allairx
      DB_USERNAME: allairx
      DB_PASSWORD: WireTrip0908@allairx
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - internal_net
    expose:
      - "9000"
    volumes:
      - laravel_code:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - internal_net
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: allairx
      MYSQL_USER: allairx
      MYSQL_PASSWORD: WireTrip0908@allairx
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/databases/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    restart: always
    depends_on:
      - mysql
    networks:
      - internal_net
    volumes:
      - /home/databases/proxysql:/var/lib/proxysql
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
    ports:
      - "6033:6033"
      - "6080:6080"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - internal_net
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    networks:
      - internal_net
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - ecommerce_app
    networks:
      - internal_net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/logs/nginx:/var/log/nginx
      - laravel_code:/var/www/html:ro
    ports:
      - "80:80"

networks:
  internal_net:
    driver: bridge
    
volumes:
  laravel_code: