version: '3.8'

services:
  laravel_app:
    image: masteransh/laravel-ecommerce-prateek:3
    deploy:
      mode: replicated
      replicas: 20
      update_config:
        parallelism: 5
        delay: 10s
    networks:
      - laravel_network
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_USERNAME=laravel
      - DB_PASSWORD=your_password
    volumes:
      - /var/www/html
    depends_on:
      - proxysql

  proxysql:
    image: proxysql/proxysql:latest
    networks:
      - laravel_network
    ports:
      - "6032:6032"
      - "6033:6033"
    volumes:
      - ./proxysql/proxysql-config.cnf:/etc/proxysql.cnf

  nginx:
    image: nginx:latest
    networks:
      - laravel_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel_app

  redis:
    image: redis:latest
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: overlay
