configs:
  nginx_conf:
    file: ./nginx.conf
  proxysql_config:
    file: ./proxysql.cnf
networks:
  internal_net:
    driver: overlay
services:
  app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        delay: 10s
        parallelism: 2
    environment:
    - APP_ENV=production
    - APP_DEBUG=false
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    expose:
    - '9000'
    image: masteransh/laravel-ecommerce-prateek:3
    networks:
      internal_net:
        aliases:
        - app
    volumes:
    - laravel_code:/var/www/html
  mysql1:
    deploy:
      placement:
        constraints:
        - node.labels.db == server1
    environment:
      MYSQL_ROOT_PASSWORD: Devilansh@123
    image: mysql:8.0
    networks:
    - internal_net
    volumes:
    - mysql1_data:/var/lib/mysql
  mysql2:
    deploy:
      placement:
        constraints:
        - node.labels.db == server2
    environment:
      MYSQL_ROOT_PASSWORD: Devilansh@123
    image: mysql:8.0
    networks:
    - internal_net
    volumes:
    - mysql2_data:/var/lib/mysql
  mysql3:
    deploy:
      placement:
        constraints:
        - node.labels.db == server3
    environment:
      MYSQL_ROOT_PASSWORD: Devilansh@123
    image: mysql:8.0
    networks:
    - internal_net
    volumes:
    - mysql3_data:/var/lib/mysql
  mysql4:
    deploy:
      placement:
        constraints:
        - node.labels.db == server4
    environment:
      MYSQL_ROOT_PASSWORD: Devilansh@123
    image: mysql:8.0
    networks:
    - internal_net
    volumes:
    - mysql4_data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
    - proxysql
    environment:
      MYSQL_ROOT_PASSWORD: Devilansh@123
      PMA_HOST: proxysql
      PMA_PORT: '6033'
    image: phpmyadmin/phpmyadmin:latest
    networks:
    - internal_net
    ports:
    - 8080:80
    restart: always
  proxysql:
    configs:
    - mode: 292
      source: proxysql_config
      target: /etc/proxysql.cnf
    depends_on: []
    deploy:
      replicas: 1
    image: proxysql/proxysql:latest
    networks:
    - internal_net
    ports:
    - 6032:6032
    - 6034:6033
  redis:
    container_name: redis
    image: redis:alpine
    networks:
    - internal_net
    ports:
    - 6379:6379
    restart: always
version: '3.8'
volumes:
  laravel_code: null
  mysql1_data: null
  mysql2_data: null
  mysql3_data: null
  mysql4_data: null
